# Generated by Django 5.0.2 on 2024-02-20 23:41

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('description_short', models.TextField(default='<Not provided>', max_length=1000)),
                ('concepts', models.TextField(blank=True, max_length=1000, null=True)),
                ('technology', models.TextField(blank=True, max_length=1000, null=True)),
                ('rank', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('github', models.URLField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True, max_length=150)),
                ('img_url', models.URLField(blank=True, max_length=150)),
                ('featured', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
